### PR TITLE
Stage 0.8

### PR DESCRIPTION
**Pull request by dim-s**

### CODE REVIEW

**Comment by BurakDev** [comment]
What about integrating java scripting platform ?

**Comment by dim-s** [comment]
@BurakDev JPHP has support of this https://github.com/jphp-compiler/jphp/tree/master/jphp-scripting

**Comment by BurakDev** [comment]
Oh okay ! Any docs/examples ?

**Comment by dim-s** [comment]
@BurakDev Documentation for this does not exist yet, but it's JSR-223 standard and you can read about it here: http://www.drdobbs.com/jvm/jsr-223-scripting-for-the-java-platform/215801163.

**Pull request closed without merging**
