### PR TITLE
Implement gettimeofday() function

### PR DESCRIPTION
**Pull request by hnw**
Hi guys,

I'm very interested in this project, so I'd like to implement some PHP functions.
First of all, I choose `gettimeofday()`.
This function is important, because it's used in `Zend/bench.php` in PHP source code.

Thanks.

### CODE REVIEW

**Comment by dim-s** [comment]
Thanks for the function :+1: 

If you want to implement functions from the zend std library, we will be glad :)

**Comment by SerafimArts** [comment]
What do u think about rename this function from `gettimeofday` to `getTimeOfDay` to match PSR agreement?

**Comment by SerafimArts** [comment]
Hmmm, this function has no `@Signature` it is not available from php. Yep? That is, I made a mistake at the expense PSR? Or something I don't know...

**Comment by dim-s** [comment]
@SerafimArts 
No, it's not a mistake. You do not need to declare `@Signature` in a FunctionsContainer, by default all public methods will be wrapped automatically.

**Comment by SerafimArts** [comment]
Снимаю вопрос, такое именование по PSR касается только методов, для публичных функций ничего не сказано, но по привычке используют underscore, по крайней мере почти во всей php stdlib.

I apologize for the false alarm +)

**Pull request merged**
